version: "3.5"
services:
  nodejs_app:
    container_name: app
    image: beng98/eng74_docker_project
    environment:
      - DB_HOST=mongodb://db:27017/posts
    links:
      - db
    ports:
      - "106:3000"

  db:
    container_name: database
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongod.conf:/etc/mongod.conf
